version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: 'postgres'
    environment:
      - POSTGRES_DB=sad_back_end
      - POSTGRES_PASSWORD=db
      - POSTGRES_USER=db
      - TZ=GMT
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432
